HW10 is completed
chirmicci/hw-test pull request #11
Opened 2024-04-30 19:10 UTC by chirmicci

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-04-30 19:26 UTC, chirmicci commented
goos: darwin
goarch: arm64
pkg: github.com/fixme_my_friend/hw10_program_optimization
BenchmarkGetDomainStat
BenchmarkGetDomainStat-12    	     660	   1698836 ns/op
PASS

2024-04-30 19:40 UTC, vladislavmass requested changes

2024-04-30 19:40 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  type users [100_000]User
А что если во входных данных будет не 100 000,а  100 001 пользователь?

2024-04-30 19:40 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  type User struct {
Нам для выполнения точно нужны все поля этой структуры ?

2024-04-30 19:40 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +	re := regexp.MustCompile("\\." + domain)
Не очень хорошая идея. Что будет если у нас в списке будет пользователь с почтой `5Moore.com@Teklist.net` и мы как раз захотим получить статистику на домене com?

2024-04-30 19:40 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  func getUsers(r io.Reader) (result users, err error) {
Мы точно хотим возвращать массив хрен знает какого размера между 2 функциями? нам вообще нужно где то хранить распаршеные значение? или может можно формировать статистику на лету?

2024-05-01 09:13 UTC, chirmicci commented on hw10_program_optimization/stats.go
>  func getUsers(r io.Reader) (result users, err error) {
я почему то думал что я не имею права удалять функции а только оптимизировать код не меняя каких то основных подходов, я был не прав)

2024-05-01 09:16 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  func getUsers(r io.Reader) (result users, err error) {
Менять нельзя только экспортируемую функцию

2024-05-01 09:33 UTC, chirmicci commented
goos: darwin
goarch: arm64
pkg: github.com/fixme_my_friend/hw10_program_optimization
BenchmarkGetDomainStat
BenchmarkGetDomainStat-12    	  892432	      1248 ns/op
PASS

после правок

2024-05-01 10:14 UTC, vladislavmass requested changes

2024-05-01 10:14 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +	re := regexp.MustCompile("\\." + domain + "$")
Всю эту историю с регулярками можно заменить на `strings.HasSuffix`. И работать будет быстрее и кода меньше.

2024-05-01 10:14 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +			result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]++
Тут будет паника если вдруг в email не будет символа `@`

2024-05-02 11:24 UTC, vladislavmass approved these changes

2024-05-02 11:24 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +		_, err := mail.ParseAddress(user.Email)
Не очень хорошая идея.

2024-05-02 11:24 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +		if err == nil && strings.HasSuffix(user.Email, "."+domain) {
Конкатенцаию `"."+domain` можно было сделать заранее и положить в переменную

2024-05-03 08:35 UTC, merged